name: MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gitmodules
        run: git submodule update --init --recursive

      - name: Build and Test
        run: ./scripts/feature-tests.shell
